# Generated by Django 4.0.4 on 2022-05-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Moving Forward', 'Moving Forward'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
    ]
