# Generated by Django 4.0.4 on 2022-05-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='link',
            field=models.URLField(default='https://www.linkedin.com/jobs/'),
        ),
    ]
