# Generated by Django 4.0.4 on 2022-05-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_profile_hobies_alter_profile_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='networks',
        ),
        migrations.AddField(
            model_name='profile',
            name='networks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
