# Generated by Django 4.0.4 on 2022-05-01 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0009_remove_profile_networks_profile_networks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='networks', to=settings.AUTH_USER_MODEL),
        ),
    ]
