# Generated by Django 4.0.4 on 2022-05-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_application_link'),
        ('main_app', '0011_profile_name'),
    ]

    operations = [
    ]
