# Generated by Django 4.0.4 on 2022-05-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hobies',
            new_name='hobbies',
        ),
    ]
