# Generated by Django 4.0.4 on 2022-05-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_hobies_profile_hobbies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='Profile',
            new_name='profile',
        ),
    ]
