# Generated by Django 4.0.4 on 2022-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_profile_avatar_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='salary',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
